In [3]:
import pandas as pd
import requests

In [4]:
#Define the website URL
   #Store the Transfermarkt webpage link inside a variable
   #This webpage contains MLS attendance and stadium information

url = "https://www.transfermarkt.us/major-league-soccer/besucherzahlen/wettbewerb/MLS1"

#Create request headers
   #Add a User-Agent to simulate a normal browser request
   #Help prevent the website from blocking the connection

headers = {
    "User-Agent": "Mozilla/5.0"
}

#Connect to the website
   #Send a request to the webpage
   #Download the HTML content from the site
response = requests.get(url, headers=headers)

#Extract HTML tables
   #Use pandas to detect all tables from the webpage
   #Store the extracted tables inside a list
tables = pd.read_html(response.text)

#Verify the scraping process
   #Count the number of tables extracted
   #Confirm that the website data was collected successfully
len(tables)

/var/folders/qx/zjy9jsyd2sg69nyf65kyxhyr0000gn/T/ipykernel_66190/3021315131.py:9: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(response.text)

29

In [ ]:
#Inspect the extracted tables
   #Loop through all extracted tables
   #Print the first rows of each table
   #Identify which table contains attendance and stadium information

for i, table in enumerate(tables):
    print(f"TABLE {i}")
    print(table.head())
    print("\n" + "-"*50 + "\n")

TABLE 0
                   0                                                  1   2
0  Filter by Season:  2026  2025  2024  2023  2022  2021  2020  2019... NaN

--------------------------------------------------

TABLE 1
     #                                 Stadium  Capacity Spectators  Average
0  1.0  Mercedes-Benz StadiumAtlanta United FC    73.019    301.014   37.627
1  NaN                   Mercedes-Benz Stadium       NaN        NaN      NaN
2  NaN                       Atlanta United FC       NaN        NaN      NaN
3  2.0               BMO StadiumLos Angeles FC    22.000    207.995   29.714
4  NaN                             BMO Stadium       NaN        NaN      NaN

--------------------------------------------------

TABLE 2
    0                      1
0 NaN  Mercedes-Benz Stadium
1 NaN      Atlanta United FC

--------------------------------------------------

TABLE 3
    0               1
0 NaN     BMO Stadium
1 NaN  Los Angeles FC

--------------------------------------------------

TABLE 4
    0                       1
0 NaN                BC Place
1 NaN  Vancouver Whitecaps FC

--------------------------------------------------

TABLE 5
    0                 1
0 NaN    Yankee Stadium
1 NaN  New York City FC

--------------------------------------------------

TABLE 6
    0                        1
0 NaN  Bank of America Stadium
1 NaN             Charlotte FC

--------------------------------------------------

TABLE 7
    0           1
0 NaN   BMO Field
1 NaN  Toronto FC

--------------------------------------------------

TABLE 8
    0                   1
0 NaN  Snapdragon Stadium
1 NaN        San Diego FC

--------------------------------------------------

TABLE 9
    0                           1
0 NaN  Dick's Sporting Goods Park
1 NaN             Colorado Rapids

--------------------------------------------------

TABLE 10
    0             1
0 NaN   GEODIS Park
1 NaN  Nashville SC

--------------------------------------------------

TABLE 11
    0                1
0 NaN    Soldier Field
1 NaN  Chicago Fire FC

--------------------------------------------------

TABLE 12
    0              1
0 NaN    TQL Stadium
1 NaN  FC Cincinnati

--------------------------------------------------

TABLE 13
    0                    1
0 NaN          Lumen Field
1 NaN  Seattle Sounders FC

--------------------------------------------------

TABLE 14
    0                           1
0 NaN  Dignity Health Sports Park
1 NaN          Los Angeles Galaxy

--------------------------------------------------

TABLE 15
    0                    1
0 NaN  America First Field
1 NaN  Real Salt Lake City

--------------------------------------------------

TABLE 16
    0           1
0 NaN  Q2 Stadium
1 NaN   Austin FC

--------------------------------------------------

TABLE 17
    0            1
0 NaN   Audi Field
1 NaN  D.C. United

--------------------------------------------------

TABLE 18
    0                        1
0 NaN  ScottsMiracle-Gro Field
1 NaN            Columbus Crew

--------------------------------------------------

TABLE 19
    0                     1
0 NaN  Shell Energy Stadium
1 NaN     Houston Dynamo FC

--------------------------------------------------

TABLE 20
    0               1
0 NaN      Nu Stadium
1 NaN  Inter Miami CF

--------------------------------------------------

TABLE 21
    0                 1
0 NaN  Inter&Co Stadium
1 NaN   Orlando City SC

--------------------------------------------------

TABLE 22
    0                     1
0 NaN           PayPal Park
1 NaN  San Jose Earthquakes

--------------------------------------------------

TABLE 23
    0                    1
0 NaN        Allianz Field
1 NaN  Minnesota United FC

--------------------------------------------------

TABLE 24
    0                 1
0 NaN   Providence Park
1 NaN  Portland Timbers

--------------------------------------------------

TABLE 25
    0                   1
0 NaN         Subaru Park
1 NaN  Philadelphia Union

--------------------------------------------------

TABLE 26
    0                  1
0 NaN     Energizer Park
1 NaN  St. Louis CITY SC

--------------------------------------------------

TABLE 27
   #  Club       Club.1  Unnamed: 3  +/-  Pts
0  1   NaN    Nashville          11   15   24
1  2   NaN  New England          11    7   22
2  3   NaN        Miami          12    5   22
3  4   NaN      Chicago          11    6   17
4  5   NaN  D.C. United          12   -2   16

--------------------------------------------------

TABLE 28
   #  Club          Club.1  Unnamed: 3  +/-  Pts
0  1   NaN  SJ Earthquakes          12   19   29
1  2   NaN       Vancouver          11   20   26
2  3   NaN            LAFC          12    8   21
3  4   NaN         Seattle          10    8   21
4  5   NaN       Minnesota          12   -2   21

--------------------------------------------------

In [7]:
#Select the attendance table
#Store the table containing stadium attendance data as the main dataframe

df = tables[1]

In [8]:
#Preview the dataframe
#Display the first rows of the attendance dataset
#Verify that the correct table was selected

df.head()

     #                                 Stadium  Capacity Spectators  Average
0  1.0  Mercedes-Benz StadiumAtlanta United FC    73.019    301.014   37.627
1  NaN                   Mercedes-Benz Stadium       NaN        NaN      NaN
2  NaN                       Atlanta United FC       NaN        NaN      NaN
3  2.0               BMO StadiumLos Angeles FC    22.000    207.995   29.714
4  NaN                             BMO Stadium       NaN        NaN      NaN

In [9]:
#Inspect the dataframe structure
#Display column names and data types
#Understand how the dataset is organized

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 76 entries, 0 to 75
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   #           25 non-null     float64
 1   Stadium     76 non-null     object
 2   Capacity    26 non-null     float64
 3   Spectators  26 non-null     object
 4   Average     26 non-null     float64
dtypes: float64(3), object(2)
memory usage: 3.1+ KB

In [10]:
#Remove rows with missing attendance values
#Keep only rows containing valid club attendance data

df = df.dropna(subset=["Average"])

In [11]:
#Preview the cleaned dataframe
#Verify that unnecessary rows were removed

df.head()

      #                                 Stadium  Capacity Spectators  Average
0   1.0  Mercedes-Benz StadiumAtlanta United FC    73.019    301.014   37.627
3   2.0               BMO StadiumLos Angeles FC    22.000    207.995   29.714
6   3.0          BC PlaceVancouver Whitecaps FC    54.500    193.515   24.189
9   4.0          Yankee StadiumNew York City FC    30.321    179.643   22.455
12  5.0     Bank of America StadiumCharlotte FC    75.412    175.686   29.281

In [12]:
#Reset the dataframe index
#Create a clean sequential index after removing rows

df = df.reset_index(drop=True)

In [13]:
#Preview the dataframe again
#Verify the updated structure and index

df.head()

     #                                 Stadium  Capacity Spectators  Average
0  1.0  Mercedes-Benz StadiumAtlanta United FC    73.019    301.014   37.627
1  2.0               BMO StadiumLos Angeles FC    22.000    207.995   29.714
2  3.0          BC PlaceVancouver Whitecaps FC    54.500    193.515   24.189
3  4.0          Yankee StadiumNew York City FC    30.321    179.643   22.455
4  5.0     Bank of America StadiumCharlotte FC    75.412    175.686   29.281